var change = true;

var messageInTime = [
      //minuto0
      [change,
        "Franchi",
        "Qué tul?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Al toque",
        null,
        "Yo armando un taller de edición de video",
        "Cuchame guach",
        null,
        "Vos vas el miércoles a lo de ceci?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "20hs creo",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Ohh",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Mmmm",
        "Muy jugado",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Pregunto!!",
        null],

      //minuto1
      [change,
        null,
        null,
        null,
        null,
        null,
        "a verrr",
        null,
        null,
        null,
        null,
        null,
        "jajajajajajaj",
        null,
        "y atom lo interpreta y te lo pinta de verde",
        null,
        null,
        null,
        null,
        null,
        "che, eso quiere decir que estás resolviendo el recu?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "no, no lo pedí",
        null,
        "ya estás probando?",
        null,
        "ay, me siento re atrasado",
        null,
        "yo estoy con electrónica",
        null,
        "y estuve toda la mañana con ort -.-",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "en este momento estamos aprendiendo amplificadores",
        null,
        null,
        "como polarizar un transistor para que amplifique",
        null,
        null,
        "haciendo que funcione en la recta de salida dentro de la zona activa",
        null],

      //minuto2
      [null,
        null,
        "y buscando el punto Q para señales",
        null,
        null,
        null,
        null,
        null,
        "intenso",
        null,
        "mañana juega argentina a las 15hs",
        null,
        "espero que mis alumnes se rateen",
        null,
        "así no tengo que dar clase",
        null,
        null,
        null,
        null,
        null,
        "jajjaj",
        null,
        null,
        "tipo me han faltado en partidos como españa y portugal",
        null,
        "y venían unos pocos",
        null,
        null,
        null,
        null,
        null,
        "viste?",
        null,
        null,
        "espero que haya 100% de deserción en la clase",
        "por arg",
        null,
        null,
        null,
        null,
        "y los que vinieron me plantean \"ay, vine a clase porque esperaba que me dejes ver el partido\"",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto3
      [change,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Es tremendo",
        null,
        "El de la almohada se ve horrible",
        null,
        null,
        null,
        null,
        null,
        "Y el del espejo es una cartera entera solo para el espejo",
        null,
        null,
        null,
        null,
        null,
        "Con la mano se fue a la mierda",
        null,
        "Es cualquiera mal mal",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Ahh",
        "Es un video estúpido",
        null,
        null,
        null,
        null,
        null,
        "Te amo 😊",
        null,
        null,
        null,
        null,
        null,
        "Nop!!!!",
        "Yo más",
        null,
        null,
        null,
        null,
        null,
        "Dale",
        null,
        "Yo en la facu leyendo",
        null,
        null,
        null],

      //minuto4
      [change,
        "hola guido!!",
        null,
        "felicidades por la muestra!!",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "sé que a veces en pla hacen encuentros con el artista que explica su obra",
        null,
        null,
        "hay algún plan de ese estilo?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Sí, me gustaría!",
        null,
        null,
        null,
        null,
        null,
        "Vos cómo estás de horarios?",
        null,
        "Muy a full?",
        null,
        null,
        null,
        null,
        null,
        "tranqui",
        null,
        null],

      //minuto5
      [null,
        null,
        null,
        null,
        "jajaj",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "okey, yo pienso terminar todo lo de los finales tranquilo y después hablarte",
        null,
        null,
        "así que la semana que viene te escribo jaja",
        null,
        null,
        null,
        null,
        null,
        "gracias!!",
        null,
        null,
        null,
        "vos vas a a seguir yendo los lunes?",
        null,
        "a la facu en el segundo cuatri, digo",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "pensé que era dos consecutivas",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "claro",
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto6
      [change,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Estoy llegando",
        null,
        "Ya te digo",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Está abierto alumnos",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Dale",
        null,
        null,
        null,
        null,
        null,
        "Qué pasó? No vas a venir?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto7
      [change,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "hoy",
        "por?",
        "turno noche",
        null,
        "qué necesitai?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "opa",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "sí",
        "se come??",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "qué mal",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "oks",
        null],

      //minuto8
      [change,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "hola isa!!",
        null,
        "el formato de video, decís?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "qué bajón!",
        null,
        null,
        "le trataste de enviar un mail a mene y ceci para advertirles?",
        null,
        null,
        null,
        null,
        null,
        null,
        "ah, bueno, te lo paso después",
        null,
        "claro, me acuerdo que nos habías contado",
        null,
        null,
        null,
        "cómo va lo de la mudanza?",
        null,
        null,
        "mirá",
        null,
        "yo estoy en mi casa",
        null,
        "no voy a poder ir hoy",
        null,
        "jaja",
        null,
        null,
        null,
        "sí, por suerte",
        null,
        "la clase pasada",
        null,
        null,
        null,
        "te tiro la posta?",
        null,
        "bajate la app HandBrake",
        null],

      //minuto9
      ["es un conversor de video",
        null,
        "yo lo uso para comprimir videos",
        null,
        "es increíble",
        null,
        "te pasa de un video de 100mb a 10mb",
        null,
        "y te lo baja en mp4",
        null,
        null,
        "lo único que tenés que hacer es importar el video en la app y poner convertir",
        null,
        "y te lo deja pipi cucú para laburar",
        null,
        null,
        null,
        null,
        null,
        "qué raro",
        null,
        "la peli la tenías bajada?",
        null,
        null,
        null,
        "okey",
        null,
        "y la importas al premiere",
        null,
        "lo que quedó choto es la extensión del archivo al final?",
        null,
        null,
        null,
        null,
        "claro",
        "quiero decir",
        null,
        "pero dentro del primere o cuando lo exportas?",
        null,
        null,
        null,
        "jajaj",
        "ok",
        null,
        "entonces hay que verlo con la compu",
        null,
        null,
        null,
        "ya sé...",
        null,
        "si querés te intento ayudar por chat",
        null,
        "pero no quiero llevarte por el camino de la frustación",
        null,
        "pero si estás dispuesta...",
        null,
        null,
        null,
        "dale",
        null],

      //minuto10
      [change,
        null,
        null,
        null,
        "sí...",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "yo estoy re quemado",
        null,
        "pero me podes preguntar",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "la resolución está en el hangout",
        null,
        "en el chat",
        null,
        null,
        null,
        null,
        null,
        "subimos fotos",
        null,
        null,
        null,
        null,
        null,
        null,
        "re copado igual",
        null,
        null,
        null,
        null,
        null,
        "claro",
        "café",
        "y siesta mañana",
        null,
        null,
        null,
        null,
        null],

      //minuto11
      [change,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Simulación?",
        null,
        null,
        null,
        null,
        null,
        "Creo que estoy quemado de la semana",
        null,
        "No recuerdo qué hicimos",
        "Qué era?",
        null,
        null,
        null,
        null,
        null,
        "Ahh de electrónica decís??",
        null,
        null,
        null,
        null,
        null,
        "Pensé que me hablabas de hipermedial",
        null,
        null,
        null,
        null,
        null,
        null,
        "http://tinyurl.com/ycq9mkes",
        null,
        null,
        null,
        null,
        null,
        null,
        "Me mareo",
        null,
        "Por eso no me sonaba",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "👍",
        null],

      //minuto12
      [change,
        null,
        null,
        null,
        null,
        null,
        "Ah bueno",
        null,
        null,
        null,
        null,
        null,
        "Qué mala",
        null,
        null,
        null,
        "Ah la birra sí",
        null,
        "Tengo que decir cuándo podría?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "No",
        null,
        "Yo no me bajo virus",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto13
      [null,
        null,
        "Cómo que apoya??",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "sí, ya sé qué decis",
        null,
        "pero apretá sobre el nombre y no pasa",
        "no?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "birra si",
        "obvio",
        null,
        "respondo por eso también?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "y sí",
        "obvio",
        "birra gratis",
        null,
        "yo la voy a tener que pagar no?",
        "ya te debo muchas",
        null,
        null,
        null],

      //minuto14
      [change,
        "Nacho!!",
        null,
        "Qué tal, tanto tiempo?",
        null,
        null,
        null,
        null,
        null,
        "También",
        null,
        "Te hablo por lo siguiente",
        null,
        null,
        "Estoy en plan de armar un libro",
        null,
        null,
        "Y javi sanko me comentó que vos te estabas dedicando a la edición de libros",
        null,
        "O algo parecido",
        null,
        null,
        "(Trabajamos juntos como docentes en ort)",
        "Es así?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "En realidad quería charla de mate y bizcochitos sobre edición",
        "Jajja",
        null,
        "Tipo más personal",
        null,
        "No estoy buscando un editor",
        null,
        null,
        null,
        "Si no consejos sobre el diseño a la hora de armar un libro"],

      //minuto15
      [null,
        null,
        null,
        null,
        null,
        "Lo del editor viene después",
        null,
        null,
        "Y ahí si te volvería a hablar",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Siento que me va a tratar de convencer de laburar en conjunto",
        null,
        null,
        null,
        "Vos creés que no?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Es con estudiantes de edición",
        null,
        "Pensé que vos estabas en esa",
        null,
        "y por eso quería charlar con vos",
        null],

      //minuto16
      [change,
        "gabo!!",
        null,
        "cómo estás?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "también",
        null,
        "tomando un descansito",
        null,
        null,
        "estoy cerrando notas de estudiantes de una materia de arte",
        null,
        null,
        "lo difícil que me es ser objetivo en eso!!",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "y sí",
        null,
        null,
        null,
        null,
        null,
        null,
        "en parte lo difícil es eso",
        null,
        "estuvimos haciendo diferentes trabajos en clase",
        null,
        "relacionados con arte y electrónia",
        "electrónica*",
        null,
        "son muy simples en electrónica, y eso no evalúo",
        null,
        null,
        "si no, me interesa ver si pudieron darle una vuelta a un proyecto tecnológico",
        null,
        "para poder dar cierto mensaje",
        null,
        "si hubo alguna sensibilidad involucrada en elles",
        null,
        "la materia se está armando",
        null,
        "así que todo está en plan \"conejillos de indias\"",
        null,
        "jajaj",
        null,
        "tus clases van bien?",
        "filosofía, no?",
        null],

      //minuto17
      [null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto18
      [null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "jajaj",
        null,
        "te comprendo",
        null,
        null,
        null,
        null,
        "y cuando le pones pilas es más cansador",
        null,
        null,
        null,
        "pero leeme, te escribía por una cosa",
        null,
        "así te traigo un poco a lo que hacés con adultos",
        null,
        null,
        "no fui al último encuentro de creative coding",
        null,
        null,
        "por la fatiga que sentía de la semana",
        null,
        null,
        "y quería encontrarte para seguir hablando",
        null,
        null,
        "de lo que me habías comentado en la charla esta que di",
        null,
        null,
        "y me gustaría leerte sobre lo que querías decir",
        null,
        "y si podés, extenderte",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto19
      [null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Yo lo leí para la facu",
        null,
        "e investigué un toque pero hasta ahí",
        null,
        null,
        "Realmente, ahora que me comentas, debería leer más el contexto",
        null,
        "Me copa hacer lo que comentas",
        null,
        "Vos decís en un plan delectro",
        null,
        "o plan codigo creativo?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Dale"],

        //minuto20
        [change,
          "Franchi",
          "Qué tul?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Al toque",
          null,
          "Yo armando un taller de edición de video",
          "Cuchame guach",
          null,
          "Vos vas el miércoles a lo de ceci?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "20hs creo",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Ohh",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Mmmm",
          "Muy jugado",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Pregunto!!",
          null],

        //minuto21
        [change,
          null,
          null,
          null,
          null,
          null,
          "a verrr",
          null,
          null,
          null,
          null,
          null,
          "jajajajajajaj",
          null,
          "y atom lo interpreta y te lo pinta de verde",
          null,
          null,
          null,
          null,
          null,
          "che, eso quiere decir que estás resolviendo el recu?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "no, no lo pedí",
          null,
          "ya estás probando?",
          null,
          "ay, me siento re atrasado",
          null,
          "yo estoy con electrónica",
          null,
          "y estuve toda la mañana con ort -.-",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "en este momento estamos aprendiendo amplificadores",
          null,
          null,
          "como polarizar un transistor para que amplifique",
          null,
          null,
          "haciendo que funcione en la recta de salida dentro de la zona activa",
          null],

        //minuto22
        [null,
          null,
          "y buscando el punto Q para señales",
          null,
          null,
          null,
          null,
          null,
          "intenso",
          null,
          "mañana juega argentina a las 15hs",
          null,
          "espero que mis alumnes se rateen",
          null,
          "así no tengo que dar clase",
          null,
          null,
          null,
          null,
          null,
          "jajjaj",
          null,
          null,
          "tipo me han faltado en partidos como españa y portugal",
          null,
          "y venían unos pocos",
          null,
          null,
          null,
          null,
          null,
          "viste?",
          null,
          null,
          "espero que haya 100% de deserción en la clase",
          "por arg",
          null,
          null,
          null,
          null,
          "y los que vinieron me plantean \"ay, vine a clase porque esperaba que me dejes ver el partido\"",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null],

        //minuto23
        [change,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Es tremendo",
          null,
          "El de la almohada se ve horrible",
          null,
          null,
          null,
          null,
          null,
          "Y el del espejo es una cartera entera solo para el espejo",
          null,
          null,
          null,
          null,
          null,
          "Con la mano se fue a la mierda",
          null,
          "Es cualquiera mal mal",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Ahh",
          "Es un video estúpido",
          null,
          null,
          null,
          null,
          null,
          "Te amo 😊",
          null,
          null,
          null,
          null,
          null,
          "Nop!!!!",
          "Yo más",
          null,
          null,
          null,
          null,
          null,
          "Dale",
          null,
          "Yo en la facu leyendo",
          null,
          null,
          null],

        //minuto24
        [change,
          "hola guido!!",
          null,
          "felicidades por la muestra!!",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "sé que a veces en pla hacen encuentros con el artista que explica su obra",
          null,
          null,
          "hay algún plan de ese estilo?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Sí, me gustaría!",
          null,
          null,
          null,
          null,
          null,
          "Vos cómo estás de horarios?",
          null,
          "Muy a full?",
          null,
          null,
          null,
          null,
          null,
          "tranqui",
          null,
          null],

        //minuto25
        [null,
          null,
          null,
          null,
          "jajaj",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "okey, yo pienso terminar todo lo de los finales tranquilo y después hablarte",
          null,
          null,
          "así que la semana que viene te escribo jaja",
          null,
          null,
          null,
          null,
          null,
          "gracias!!",
          null,
          null,
          null,
          "vos vas a a seguir yendo los lunes?",
          null,
          "a la facu en el segundo cuatri, digo",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "pensé que era dos consecutivas",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "claro",
          null,
          null,
          null,
          null,
          null,
          null],

        //minuto26
        [change,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Estoy llegando",
          null,
          "Ya te digo",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Está abierto alumnos",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Dale",
          null,
          null,
          null,
          null,
          null,
          "Qué pasó? No vas a venir?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null],

        //minuto27
        [change,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "hoy",
          "por?",
          "turno noche",
          null,
          "qué necesitai?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "opa",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "sí",
          "se come??",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "qué mal",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "oks",
          null],

        //minuto28
        [change,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "hola isa!!",
          null,
          "el formato de video, decís?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "qué bajón!",
          null,
          null,
          "le trataste de enviar un mail a mene y ceci para advertirles?",
          null,
          null,
          null,
          null,
          null,
          null,
          "ah, bueno, te lo paso después",
          null,
          "claro, me acuerdo que nos habías contado",
          null,
          null,
          null,
          "cómo va lo de la mudanza?",
          null,
          null,
          "mirá",
          null,
          "yo estoy en mi casa",
          null,
          "no voy a poder ir hoy",
          null,
          "jaja",
          null,
          null,
          null,
          "sí, por suerte",
          null,
          "la clase pasada",
          null,
          null,
          null,
          "te tiro la posta?",
          null,
          "bajate la app HandBrake",
          null],

        //minuto29
        ["es un conversor de video",
          null,
          "yo lo uso para comprimir videos",
          null,
          "es increíble",
          null,
          "te pasa de un video de 100mb a 10mb",
          null,
          "y te lo baja en mp4",
          null,
          null,
          "lo único que tenés que hacer es importar el video en la app y poner convertir",
          null,
          "y te lo deja pipi cucú para laburar",
          null,
          null,
          null,
          null,
          null,
          "qué raro",
          null,
          "la peli la tenías bajada?",
          null,
          null,
          null,
          "okey",
          null,
          "y la importas al premiere",
          null,
          "lo que quedó choto es la extensión del archivo al final?",
          null,
          null,
          null,
          null,
          "claro",
          "quiero decir",
          null,
          "pero dentro del primere o cuando lo exportas?",
          null,
          null,
          null,
          "jajaj",
          "ok",
          null,
          "entonces hay que verlo con la compu",
          null,
          null,
          null,
          "ya sé...",
          null,
          "si querés te intento ayudar por chat",
          null,
          "pero no quiero llevarte por el camino de la frustación",
          null,
          "pero si estás dispuesta...",
          null,
          null,
          null,
          "dale",
          null],

        //minuto30
        [change,
          null,
          null,
          null,
          "sí...",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "yo estoy re quemado",
          null,
          "pero me podes preguntar",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "la resolución está en el hangout",
          null,
          "en el chat",
          null,
          null,
          null,
          null,
          null,
          "subimos fotos",
          null,
          null,
          null,
          null,
          null,
          null,
          "re copado igual",
          null,
          null,
          null,
          null,
          null,
          "claro",
          "café",
          "y siesta mañana",
          null,
          null,
          null,
          null,
          null],

        //minuto31
        [change,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Simulación?",
          null,
          null,
          null,
          null,
          null,
          "Creo que estoy quemado de la semana",
          null,
          "No recuerdo qué hicimos",
          "Qué era?",
          null,
          null,
          null,
          null,
          null,
          "Ahh de electrónica decís??",
          null,
          null,
          null,
          null,
          null,
          "Pensé que me hablabas de hipermedial",
          null,
          null,
          null,
          null,
          null,
          null,
          "http://tinyurl.com/ycq9mkes",
          null,
          null,
          null,
          null,
          null,
          null,
          "Me mareo",
          null,
          "Por eso no me sonaba",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "👍",
          null],

        //minuto32
        [change,
          null,
          null,
          null,
          null,
          null,
          "Ah bueno",
          null,
          null,
          null,
          null,
          null,
          "Qué mala",
          null,
          null,
          null,
          "Ah la birra sí",
          null,
          "Tengo que decir cuándo podría?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "No",
          null,
          "Yo no me bajo virus",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null],

        //minuto33
        [null,
          null,
          "Cómo que apoya??",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "sí, ya sé qué decis",
          null,
          "pero apretá sobre el nombre y no pasa",
          "no?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "birra si",
          "obvio",
          null,
          "respondo por eso también?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "y sí",
          "obvio",
          "birra gratis",
          null,
          "yo la voy a tener que pagar no?",
          "ya te debo muchas",
          null,
          null,
          null],

        //minuto34
        [change,
          "Nacho!!",
          null,
          "Qué tal, tanto tiempo?",
          null,
          null,
          null,
          null,
          null,
          "También",
          null,
          "Te hablo por lo siguiente",
          null,
          null,
          "Estoy en plan de armar un libro",
          null,
          null,
          "Y javi sanko me comentó que vos te estabas dedicando a la edición de libros",
          null,
          "O algo parecido",
          null,
          null,
          "(Trabajamos juntos como docentes en ort)",
          "Es así?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "En realidad quería charla de mate y bizcochitos sobre edición",
          "Jajja",
          null,
          "Tipo más personal",
          null,
          "No estoy buscando un editor",
          null,
          null,
          null,
          "Si no consejos sobre el diseño a la hora de armar un libro"],

        //minuto35
        [null,
          null,
          null,
          null,
          null,
          "Lo del editor viene después",
          null,
          null,
          "Y ahí si te volvería a hablar",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Siento que me va a tratar de convencer de laburar en conjunto",
          null,
          null,
          null,
          "Vos creés que no?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Es con estudiantes de edición",
          null,
          "Pensé que vos estabas en esa",
          null,
          "y por eso quería charlar con vos",
          null],

        //minuto36
        [change,
          "gabo!!",
          null,
          "cómo estás?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "también",
          null,
          "tomando un descansito",
          null,
          null,
          "estoy cerrando notas de estudiantes de una materia de arte",
          null,
          null,
          "lo difícil que me es ser objetivo en eso!!",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "y sí",
          null,
          null,
          null,
          null,
          null,
          null,
          "en parte lo difícil es eso",
          null,
          "estuvimos haciendo diferentes trabajos en clase",
          null,
          "relacionados con arte y electrónia",
          "electrónica*",
          null,
          "son muy simples en electrónica, y eso no evalúo",
          null,
          null,
          "si no, me interesa ver si pudieron darle una vuelta a un proyecto tecnológico",
          null,
          "para poder dar cierto mensaje",
          null,
          "si hubo alguna sensibilidad involucrada en elles",
          null,
          "la materia se está armando",
          null,
          "así que todo está en plan \"conejillos de indias\"",
          null,
          "jajaj",
          null,
          "tus clases van bien?",
          "filosofía, no?",
          null],

        //minuto37
        [null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null],

        //minuto38
        [null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "jajaj",
          null,
          "te comprendo",
          null,
          null,
          null,
          null,
          "y cuando le pones pilas es más cansador",
          null,
          null,
          null,
          "pero leeme, te escribía por una cosa",
          null,
          "así te traigo un poco a lo que hacés con adultos",
          null,
          null,
          "no fui al último encuentro de creative coding",
          null,
          null,
          "por la fatiga que sentía de la semana",
          null,
          null,
          "y quería encontrarte para seguir hablando",
          null,
          null,
          "de lo que me habías comentado en la charla esta que di",
          null,
          null,
          "y me gustaría leerte sobre lo que querías decir",
          null,
          "y si podés, extenderte",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null],

        //minuto39
        [null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Yo lo leí para la facu",
          null,
          "e investigué un toque pero hasta ahí",
          null,
          null,
          "Realmente, ahora que me comentas, debería leer más el contexto",
          null,
          "Me copa hacer lo que comentas",
          null,
          "Vos decís en un plan delectro",
          null,
          "o plan codigo creativo?",
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          "Dale"],

          //minuto40
          [change,
            "Franchi",
            "Qué tul?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Al toque",
            null,
            "Yo armando un taller de edición de video",
            "Cuchame guach",
            null,
            "Vos vas el miércoles a lo de ceci?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "20hs creo",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Ohh",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Mmmm",
            "Muy jugado",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Pregunto!!",
            null],

          //minuto41
          [change,
            null,
            null,
            null,
            null,
            null,
            "a verrr",
            null,
            null,
            null,
            null,
            null,
            "jajajajajajaj",
            null,
            "y atom lo interpreta y te lo pinta de verde",
            null,
            null,
            null,
            null,
            null,
            "che, eso quiere decir que estás resolviendo el recu?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "no, no lo pedí",
            null,
            "ya estás probando?",
            null,
            "ay, me siento re atrasado",
            null,
            "yo estoy con electrónica",
            null,
            "y estuve toda la mañana con ort -.-",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "en este momento estamos aprendiendo amplificadores",
            null,
            null,
            "como polarizar un transistor para que amplifique",
            null,
            null,
            "haciendo que funcione en la recta de salida dentro de la zona activa",
            null],

          //minuto42
          [null,
            null,
            "y buscando el punto Q para señales",
            null,
            null,
            null,
            null,
            null,
            "intenso",
            null,
            "mañana juega argentina a las 15hs",
            null,
            "espero que mis alumnes se rateen",
            null,
            "así no tengo que dar clase",
            null,
            null,
            null,
            null,
            null,
            "jajjaj",
            null,
            null,
            "tipo me han faltado en partidos como españa y portugal",
            null,
            "y venían unos pocos",
            null,
            null,
            null,
            null,
            null,
            "viste?",
            null,
            null,
            "espero que haya 100% de deserción en la clase",
            "por arg",
            null,
            null,
            null,
            null,
            "y los que vinieron me plantean \"ay, vine a clase porque esperaba que me dejes ver el partido\"",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null],

          //minuto43
          [change,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Es tremendo",
            null,
            "El de la almohada se ve horrible",
            null,
            null,
            null,
            null,
            null,
            "Y el del espejo es una cartera entera solo para el espejo",
            null,
            null,
            null,
            null,
            null,
            "Con la mano se fue a la mierda",
            null,
            "Es cualquiera mal mal",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Ahh",
            "Es un video estúpido",
            null,
            null,
            null,
            null,
            null,
            "Te amo 😊",
            null,
            null,
            null,
            null,
            null,
            "Nop!!!!",
            "Yo más",
            null,
            null,
            null,
            null,
            null,
            "Dale",
            null,
            "Yo en la facu leyendo",
            null,
            null,
            null],

          //minuto44
          [change,
            "hola guido!!",
            null,
            "felicidades por la muestra!!",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "sé que a veces en pla hacen encuentros con el artista que explica su obra",
            null,
            null,
            "hay algún plan de ese estilo?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Sí, me gustaría!",
            null,
            null,
            null,
            null,
            null,
            "Vos cómo estás de horarios?",
            null,
            "Muy a full?",
            null,
            null,
            null,
            null,
            null,
            "tranqui",
            null,
            null],

          //minuto45
          [null,
            null,
            null,
            null,
            "jajaj",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "okey, yo pienso terminar todo lo de los finales tranquilo y después hablarte",
            null,
            null,
            "así que la semana que viene te escribo jaja",
            null,
            null,
            null,
            null,
            null,
            "gracias!!",
            null,
            null,
            null,
            "vos vas a a seguir yendo los lunes?",
            null,
            "a la facu en el segundo cuatri, digo",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "pensé que era dos consecutivas",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "claro",
            null,
            null,
            null,
            null,
            null,
            null],

          //minuto46
          [change,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Estoy llegando",
            null,
            "Ya te digo",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Está abierto alumnos",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Dale",
            null,
            null,
            null,
            null,
            null,
            "Qué pasó? No vas a venir?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null],

          //minuto47
          [change,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "hoy",
            "por?",
            "turno noche",
            null,
            "qué necesitai?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "opa",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "sí",
            "se come??",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "qué mal",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "oks",
            null],

          //minuto48
          [change,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "hola isa!!",
            null,
            "el formato de video, decís?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "qué bajón!",
            null,
            null,
            "le trataste de enviar un mail a mene y ceci para advertirles?",
            null,
            null,
            null,
            null,
            null,
            null,
            "ah, bueno, te lo paso después",
            null,
            "claro, me acuerdo que nos habías contado",
            null,
            null,
            null,
            "cómo va lo de la mudanza?",
            null,
            null,
            "mirá",
            null,
            "yo estoy en mi casa",
            null,
            "no voy a poder ir hoy",
            null,
            "jaja",
            null,
            null,
            null,
            "sí, por suerte",
            null,
            "la clase pasada",
            null,
            null,
            null,
            "te tiro la posta?",
            null,
            "bajate la app HandBrake",
            null],

          //minuto49
          ["es un conversor de video",
            null,
            "yo lo uso para comprimir videos",
            null,
            "es increíble",
            null,
            "te pasa de un video de 100mb a 10mb",
            null,
            "y te lo baja en mp4",
            null,
            null,
            "lo único que tenés que hacer es importar el video en la app y poner convertir",
            null,
            "y te lo deja pipi cucú para laburar",
            null,
            null,
            null,
            null,
            null,
            "qué raro",
            null,
            "la peli la tenías bajada?",
            null,
            null,
            null,
            "okey",
            null,
            "y la importas al premiere",
            null,
            "lo que quedó choto es la extensión del archivo al final?",
            null,
            null,
            null,
            null,
            "claro",
            "quiero decir",
            null,
            "pero dentro del primere o cuando lo exportas?",
            null,
            null,
            null,
            "jajaj",
            "ok",
            null,
            "entonces hay que verlo con la compu",
            null,
            null,
            null,
            "ya sé...",
            null,
            "si querés te intento ayudar por chat",
            null,
            "pero no quiero llevarte por el camino de la frustación",
            null,
            "pero si estás dispuesta...",
            null,
            null,
            null,
            "dale",
            null],

          //minuto50
          [change,
            null,
            null,
            null,
            "sí...",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "yo estoy re quemado",
            null,
            "pero me podes preguntar",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "la resolución está en el hangout",
            null,
            "en el chat",
            null,
            null,
            null,
            null,
            null,
            "subimos fotos",
            null,
            null,
            null,
            null,
            null,
            null,
            "re copado igual",
            null,
            null,
            null,
            null,
            null,
            "claro",
            "café",
            "y siesta mañana",
            null,
            null,
            null,
            null,
            null],

          //minuto51
          [change,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Simulación?",
            null,
            null,
            null,
            null,
            null,
            "Creo que estoy quemado de la semana",
            null,
            "No recuerdo qué hicimos",
            "Qué era?",
            null,
            null,
            null,
            null,
            null,
            "Ahh de electrónica decís??",
            null,
            null,
            null,
            null,
            null,
            "Pensé que me hablabas de hipermedial",
            null,
            null,
            null,
            null,
            null,
            null,
            "http://tinyurl.com/ycq9mkes",
            null,
            null,
            null,
            null,
            null,
            null,
            "Me mareo",
            null,
            "Por eso no me sonaba",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "👍",
            null],

          //minuto52
          [change,
            null,
            null,
            null,
            null,
            null,
            "Ah bueno",
            null,
            null,
            null,
            null,
            null,
            "Qué mala",
            null,
            null,
            null,
            "Ah la birra sí",
            null,
            "Tengo que decir cuándo podría?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "No",
            null,
            "Yo no me bajo virus",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null],

          //minuto53
          [null,
            null,
            "Cómo que apoya??",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "sí, ya sé qué decis",
            null,
            "pero apretá sobre el nombre y no pasa",
            "no?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "birra si",
            "obvio",
            null,
            "respondo por eso también?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "y sí",
            "obvio",
            "birra gratis",
            null,
            "yo la voy a tener que pagar no?",
            "ya te debo muchas",
            null,
            null,
            null],

          //minuto54
          [change,
            "Nacho!!",
            null,
            "Qué tal, tanto tiempo?",
            null,
            null,
            null,
            null,
            null,
            "También",
            null,
            "Te hablo por lo siguiente",
            null,
            null,
            "Estoy en plan de armar un libro",
            null,
            null,
            "Y javi sanko me comentó que vos te estabas dedicando a la edición de libros",
            null,
            "O algo parecido",
            null,
            null,
            "(Trabajamos juntos como docentes en ort)",
            "Es así?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "En realidad quería charla de mate y bizcochitos sobre edición",
            "Jajja",
            null,
            "Tipo más personal",
            null,
            "No estoy buscando un editor",
            null,
            null,
            null,
            "Si no consejos sobre el diseño a la hora de armar un libro"],

          //minuto55
          [null,
            null,
            null,
            null,
            null,
            "Lo del editor viene después",
            null,
            null,
            "Y ahí si te volvería a hablar",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Siento que me va a tratar de convencer de laburar en conjunto",
            null,
            null,
            null,
            "Vos creés que no?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Es con estudiantes de edición",
            null,
            "Pensé que vos estabas en esa",
            null,
            "y por eso quería charlar con vos",
            null],

          //minuto56
          [change,
            "gabo!!",
            null,
            "cómo estás?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "también",
            null,
            "tomando un descansito",
            null,
            null,
            "estoy cerrando notas de estudiantes de una materia de arte",
            null,
            null,
            "lo difícil que me es ser objetivo en eso!!",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "y sí",
            null,
            null,
            null,
            null,
            null,
            null,
            "en parte lo difícil es eso",
            null,
            "estuvimos haciendo diferentes trabajos en clase",
            null,
            "relacionados con arte y electrónia",
            "electrónica*",
            null,
            "son muy simples en electrónica, y eso no evalúo",
            null,
            null,
            "si no, me interesa ver si pudieron darle una vuelta a un proyecto tecnológico",
            null,
            "para poder dar cierto mensaje",
            null,
            "si hubo alguna sensibilidad involucrada en elles",
            null,
            "la materia se está armando",
            null,
            "así que todo está en plan \"conejillos de indias\"",
            null,
            "jajaj",
            null,
            "tus clases van bien?",
            "filosofía, no?",
            null],

          //minuto57
          [null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null],

          //minuto58
          [null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "jajaj",
            null,
            "te comprendo",
            null,
            null,
            null,
            null,
            "y cuando le pones pilas es más cansador",
            null,
            null,
            null,
            "pero leeme, te escribía por una cosa",
            null,
            "así te traigo un poco a lo que hacés con adultos",
            null,
            null,
            "no fui al último encuentro de creative coding",
            null,
            null,
            "por la fatiga que sentía de la semana",
            null,
            null,
            "y quería encontrarte para seguir hablando",
            null,
            null,
            "de lo que me habías comentado en la charla esta que di",
            null,
            null,
            "y me gustaría leerte sobre lo que querías decir",
            null,
            "y si podés, extenderte",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null],

          //minuto59
          [null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Yo lo leí para la facu",
            null,
            "e investigué un toque pero hasta ahí",
            null,
            null,
            "Realmente, ahora que me comentas, debería leer más el contexto",
            null,
            "Me copa hacer lo que comentas",
            null,
            "Vos decís en un plan delectro",
            null,
            "o plan codigo creativo?",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Dale"],
          ];
