var messageinTime = [
  //minuto0
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto1
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto2
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto3
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto4
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto5
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto6
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto7
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto8
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto9
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto10
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto11
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto12
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto13
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto14
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto15
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto16
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto17
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto18
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto19
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto20
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto21
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto22
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto23
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto24
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto25
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto26
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto27
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto28
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto29
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto30
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto31
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto32
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto33
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto34
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto35
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto36
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto37
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto38
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto39
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto40
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto41
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto42
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto43
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto44
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto45
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto46
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto47
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto48
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto49
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto50
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto51
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto52
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto53
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto54
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto55
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto56
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto57
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto58
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
  //minuto59
  [null, "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", null, "once", "doce", "trece", "catorce", "quince", "diecieis", "diecisiete", "dieciocho", "diecinueve", null, "veintiuno", "veintidos", "veintitres", "veinticuatro", "veinticinco", "veintiseis", "veintisiete", "veintiocho", "veintinueve", null, "treintaiuno", "treintaidos", "treintaitres", "treintaicuatro", "treintaicinco", "treintaiseis", "treintaisiete", "treintaiocho", "treintainueve", null, "cuarentaiuno", "cuarentaidos", "cuarentaitres", "cuarentaicuatro", "cuarentaicinco", "cuarentaiseis", "cuarentaisiete", "cuarentaiocho", "cuarentainueve", null, "cincuentaiuno", "cincuentaidos", "cincuentaitres", "cincuentaicuatro", "cincuentaicinco", "cincuentaiseis", "cincuentaisiete", "cincuentaiocho", "cincuentainueve"],
];
