var change = true;

var messageInTime = [
  //minuto0
  [change,
    null,
    null,
    null,
    null,
    "Que onda kevo",
    null,
    "Aca ensayando con el sub",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Re quiero",
    null,
    "Pero tengo el finao de cuestiones",
    null,
    "A que hora es?",
    "Sabes?",
    null,
    null,
    null,
    null,
    "Mmhhmhm me parece que no llego",
    null,
    "Re triste",
    null,
    null,
    null,
    null,
    null,
    "Taba re manija de ambisonics",
    null,
    "Osea a menos de que me tome primer9",
    null,
    null,
    null,
    null,
    null,
    null,
    "Pero no estoy en condiciones de exigir mucho a la catedra",
    null,
    null,
    "Si",
    "Re",
    null,
    "Che hablando de todo un poco",
    null,
    null,
    "Si sigue en pie la linea de esos llaveritxs pañuelo veree",
    null,
    "Me encargas uno?",
    null,
    null,
    null,
    null],

  //minuto1
  [change,
    "cuando ves lo que estás tipeando en Atom",
    null,
    "y te das cuenta que la situación social se filtra por todos lados",
    null,
    null,
    null,
    null,
    null,
    "body.removeChild()",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "XD",
    null,
    null,
    null,
    null,
    null,
    "no",
    null,
    "probando cosas del final",
    null,
    "lo tenés ?",
    "pasalo",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "uf",
    null,
    "es que si no no voy a llegar",
    null,
    "cómo es electrónica ?",
    null,
    "quiero decír en qué andan ?",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null],

  //minuto2
  [null,
    null,
    null,
    null,
    null,
    "cool",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "jaja",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "que internacionales",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "bueeeeena",
    null,
    null,
    "ni que fuera obligatorio ver el partido",
    null,
    "encima de otra selección",
    null,
    "amonestaciones",
    "mínimo",
    null,
    null,
    "amonestación, para usar una expresión futbolera",
    null,
    null,
    null,
    null,
    null],

  //minuto3
  [change,
    "No me pareció que todo esté mal",
    null,
    "Pero me dió mucha tristesa el primero",
    null,
    "Ese palo mano de selfi me dio ganas de llorar posta",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Si, pero pasa no muchas manualidades",
    null,
    null,
    null,
    null,
    null,
    "La mano fue una clara muestra de nuestra generación aislada y exhibicionista",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "No bobis no es ina cartera para un espejo",
    null,
    "Es un sobre( asi se llama ese tipo de carteras) con un espejo,",
    null,
    null,
    "la boluda del video no le puso nada pero las.minas usamos carteras chicas",
    null,
    null,
    null,
    null,
    null,
    "Si muy",
    null,
    null,
    null,
    null,
    null,
    "Yo mas",
    "Lo sabias?",
    null,
    null,
    null,
    null,
    "Yo igual",
    null,
    "Chenmenfui a bañar",
    null,
    "😍",
    null,
    null,
    null,
    "Ooh",
    null],

  //minuto4
  [change,
    null,
    null,
    null,
    null,
    null,
    "hola!",
    "gracias!",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "si, el día del cierre seguro.",
    null,
    null,
    "y el 4/8 hacemos un encuentro más técnico con los ploters,",
    null,
    null,
    null,
    null,
    "ver como andan, \"imprimí lo q hiciste en processing\" etc...",
    null,
    null,
    null,
    null,
    "pero la curadora está de viaje en ese momento,",
    null,
    null,
    null,
    "así q las conversaciones las dejamos para el final",
    null,
    null,
    null,
    "igual yo voy a estar yendo,",
    null,
    "si te dan ganas en otro momento, arreglamos y nos vemos ahi.",
    null,
    null,
    null,
    null,
    null,
    "bueno, escribime y arreglamos, pla abre de mier a sab de 15 a 20hs.",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "tengo dos meses de reuniones atrasadas jeje",
    null,
    null,
    null,
    null,
    null],

  //minuto5
  [null,
    null,
    "o sea, tengo un montón de tiempo, pero muy salteado / intermitente",
    null,
    null,
    null,
    null,
    "pero juev o sábado seguro voy a estar en la galería...",
    null,
    null,
    "decime vos cuando sepas y vemos.",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "eso. dale, suerte en los finales.",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "nop.",
    null,
    null,
    "nuestra materia es solo de primer cuat.",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "nono. osea, img electronica 2 se da ahora en el segundo,",
    null,
    null,
    "pero nosotros no estamos en esa materia... ",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null],

  //minuto6
  [change,
    "habrá certificados hoy?",
    null,
    "hay depa de alumnos?",
    null,
    null,
    "estoy terminando de subir mi entrega y salgo para caseros",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "saliendo!!!",
    null,
    "si tenés recreo... podrías pedir un certi?",
    null,
    null,
    null,
    "porfis",
    "porfis",
    null,
    null,
    null,
    null,
    null,
    null,
    "gracias Kvzi",
    null,
    null,
    null,
    null,
    null,
    "sí voy",
    null,
    null,
    "pero recién termino de subir todo al Drive para entregar",
    null,
    null,
    "estoy en REtiro",
    null,
    "odio al tren S Martín",
    null,
    "voy a por el 53 en Constitución",
    "gracias Kevz",
    null],

  //minuto7
  [change,
    "kev cuando vas a la facu ?",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "tengo algo para vos",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "hipermedial, no ?",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "ajajja, y se podría comer .. no lo recomiendo",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "hoy em acerco a la facu y te lo doy",
    null,
    null,
    null,
    null,
    null,
    null],

  //minuto8
  [change,
    "hola Kev, ya estoy saliendo para la facu",
    null,
    "che, no pude hacer el video",
    null,
    "digamos que ableton no soporta mi formato",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "si 😕",
    null,
    "no pude hacer nada",
    null,
    null,
    "lo exporté en quick time como leí y nada",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "no, no tengo los mails",
    null,
    "y estoy en plena mudanza y con muchas cosas",
    null,
    null,
    null,
    null,
    "gracias!!",
    null,
    "si podes darme una mano luego con ese tema, sería genial",
    null,
    "no se si ir 😕",
    "bien, mudándome",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "ah",
    "jaja",
    "ya mostraste?",
    null,
    null,
    null,
    "ahh",
    "okk",
    "ohh",
    null,
    "si",
    null,
    null],

  //minuto9
  [null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "pasa que yo saque una escena de una película de 2hs y media",
    null,
    "y me quedó como el ogt en el premier",
    null,
    null,
    null,
    null,
    null,
    "si",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "no se",
    "se ve mal",
    null,
    null,
    null,
    null,
    null,
    null,
    "ni idea xq como ya no me acuerdo cómo usarlo 🙍🏼💁🏼",
    null,
    null,
    null,
    null,
    null,
    null,
    "😓",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "si!!! tengop que terminar unos asuntos urgentes y te escribo, dale?",
    null,
    null,
    null],

  //minuto10
  [change,
    "ya terminaron de hangout no?",
    null,
    null,
    null,
    null,
    null,
    "si escribieron un resumen o algo me pasas?",
    null,
    null,
    "si tenes los resultados de los ejercicios me los pasas?",
    "gracias",
    "jajaja",
    null,
    null,
    "yo recien llego a casa tuve una fecha a beneficio en avellaneda",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "yo tambien...",
    null,
    null,
    "me sirve si me pasas unos screenshots de lo que tengan",
    null,
    "asi estudio y comparo",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "de una",
    "a ver",
    null,
    null,
    null,
    null,
    "de una genial, me doy una ducha y lo chequeo",
    null,
    "estoy quemadisimo de arte al aire libre yo...",
    null,
    null,
    null,
    "Si, re, pero no estoy ni ahi preparado para el parcial",
    null,
    "asique le tengo que meter ahora",
    null,
    null,
    null,
    null,
    null,
    "exacto",
    null,
    "cme doy una ducha para arrancar con eso",
    "jejeje"],

  //minuto11
  [change,
    "Hola ñeri como estas?",
    null,
    null,
    "Che vos tendras para pasarme la simulacion de la clase pasada?",
    null,
    null,
    "Estamos con agus las pe y no estamos pudoendo hacerla bien.",
    null,
    null,
    null,
    null,
    null,
    "La de la web",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "El circuito del proyecto",
    null,
    null,
    null,
    null,
    null,
    "Esacto",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Estamos cursando las mismas mal",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Muchas gracias kev",
    null,
    null,
    "Estabamos re trabados",
    null,
    null,
    null,
    null,
    null,
    null],

  //minuto12
  [change,
    "?",
    null,
    "yo no te saludé! que le pasa",
    null,
    null,
    null,
    null,
    null,
    "si te iba a decir que",
    null,
    null,
    "de la birra no vas  a decir nada?",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "ey que onda",
    null,
    "estoy saludando a todo el mundo",
    null,
    "a vos también te pasA?",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "cuando apoyo la flechita en alguien para abrir ventana de chat los saluda",
    "o sea",
    null,
    "no, pero probá esto",
    null,
    null,
    null,
    null,
    "apoyá a ver si aparece la manito",
    null,
    null,
    null,
    "y si das click para abrir",
    "los saluda!",
    null,
    null,
    null,
    null,
    "abre la ventana y automáticamente saluda",
    null,
    null,
    null,
    null,
    "probá conmigo",
    null],

  //minuto13
  [null,
    null,
    null,
    null,
    null,
    "barra derecha",
    null,
    "donde están los contactos",
    null,
    null,
    "en mi caso en gris porque tengo el chat cerrado",
    null,
    null,
    "pongo la flechita arriba de un contacto x",
    null,
    "sin dar click y me aparece la manito",
    null,
    null,
    "si doy click, abre ventana y manda automáticamente saludo",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "uh en mi caso si",
    null,
    "no puedo parar de saludar gente",
    null,
    null,
    "que gato, de donde me automatizó esto'",
    "bueno",
    "en fin",
    null,
    "birra si entonces",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "no, ya está ahora ya lo sé",
    null,
    "hasta ahora todos quieren birra",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "jajaja",
    "obvio"],

  //minuto14
  [change,
    null,
    null,
    null,
    null,
    null,
    "Kevin! Todo tranquilo, vos?",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Soy bibliotecario",
    null,
    "Trabajé con editores",
    null,
    null,
    null,
    "pero en la parte comercial",
    "no literatia.",
    null,
    null,
    null,
    null,
    null,
    null,
    "Igual si me das unos días intento ubicar algún editor",
    null,
    "y te pongo en contacto",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null],

  //minuto15
  [null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Te aconsejo igual hablar con alguien de edición",
    "jaja",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Avisame y te busco el contacto",
    null,
    null,
    "Yo creo que un editor te va a dar su idea",
    null,
    null,
    null,
    "y proponerte trabajar con su idea",
    null,
    "que es lógico",
    null,
    null,
    null,
    "porque al ser un profesional tiene su verdad",
    null,
    "no es que lo hace de pesado",
    null,
    null,
    null,
    null,
    null,
    "Pero sino charlar con estudiantes de edición es un golazo",
    null,
    null,
    "Igual no entendí si la charla la buscabas conmigo jaja",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null],

  //minuto16
  [change,
    null,
    null,
    null,
    null,
    null,
    "Kev😊",
    "Todo ok",
    "Vos?",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Jaja",
    "y bueno.",
    null,
    null,
    "Tenés que establecer los parámetros de objetividad",
    null,
    null,
    null,
    null,
    "Y cuáles son?",
    "Qué evaluás?",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null],

  //minuto17
  [null,
    "Sí.",
    null,
    "Van bien pero estoy un poco agotado la verdad.",
    null,
    null,
    "Tengo ganas de trabajar en otros espacios y niveles.",
    null,
    "Yo doy filosofía para niñxs.",
    null,
    null,
    "En un momento tenía desde sala de 4 años!",
    null,
    null,
    null,
    "Está buenísimo pero te deja exhausto",
    null,
    null,
    "y además la institución primaria e inicial",
    null,
    null,
    null,
    "es insoportable respecto de las formalidades.",
    null,
    null,
    null,
    null,
    "También me desalienta que es una responsabilidad gigante",
    null,
    null,
    "y se paga menos que lo demás.",
    null,
    null,
    null,
    "Me gustaría trabajar en algo más cercano al arte quizás",
    "no sé.",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Consideré hacer la maestría por ejemplo de la untref",
    "pero ni sé.",
    null,
    null,
    null,
    null,
    null,
    null,
    "Estoy con ganas de cambiar",
    null,
    null,
    "La propuesta con niñxs está alucinante didácticamente",
    null,
    null,
    null,
    null,
    "porque es filosofar con ellxs pero quedás de cama."],

  //minuto18
  [null,
    null,
    null,
    "Me fui curtiendo mucho con los años",
    null,
    null,
    null,
    "pero también dejando un poco todo lo que hacía con adultos.",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Dale obvio",
    null,
    "Lo que yo te dije",
    null,
    null,
    "no era respecto de incluir carteles de campañas electorales",
    null,
    "sino que te preguntaba si habías pensado",
    null,
    null,
    "en el contexto político en el que los situacionistas plantearon la deriva.",
    null,
    null,
    null,
    null],

  //minuto19
  [null,
    "El situacionismo era una práctica política concreta que",
    "por ejemplo",
    null,
    "cuestionaba la enajenación del arte",
    null,
    "so el placer como esferas específicas",
    null,
    "o separadas de la vida.",
    "O sea",
    null,
    "no era una propuesta estética",
    null,
    null,
    "o, en tanto propuesta estética pierde su sentido político.",
    "Jaja",
    null,
    "pensé que eta una pavada",
    null,
    null,
    null,
    "pero ahora que te voy escribiendo me doy cuenta de que por ahí da para largo.",
    null,
    "Yo soy bastante fan de Debord la verdad.",
    null,
    "Un día podríamos hacer una juntada para ver una peli suya",
    null,
    null,
    "y yo hago una introducción si les parece.",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Delectro supongo.",
    null,
    null,
    "No le veo relación muy clara con la cuestión del código",
    null,
    "(si con lenguaje pero eso es otra cosa)",
    null,
    "Mirate \"crítica de la separación\".",
    null,
    "Es un corto y es genial, es intenso igual.",
    null,
    null,
    null,
    null],

    //minuto20
    [change,
      null,
      null,
      null,
      null,
      "Que onda kevo",
      null,
      "Aca ensayando con el sub",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Re quiero",
      null,
      "Pero tengo el finao de cuestiones",
      null,
      "A que hora es?",
      "Sabes?",
      null,
      null,
      null,
      null,
      "Mmhhmhm me parece que no llego",
      null,
      "Re triste",
      null,
      null,
      null,
      null,
      null,
      "Taba re manija de ambisonics",
      null,
      "Osea a menos de que me tome primer9",
      null,
      null,
      null,
      null,
      null,
      null,
      "Pero no estoy en condiciones de exigir mucho a la catedra",
      null,
      null,
      "Si",
      "Re",
      null,
      "Che hablando de todo un poco",
      null,
      null,
      "Si sigue en pie la linea de esos llaveritxs pañuelo veree",
      null,
      "Me encargas uno?",
      null,
      null,
      null,
      null],

    //minuto21
    [change,
      "cuando ves lo que estás tipeando en Atom",
      null,
      "y te das cuenta que la situación social se filtra por todos lados",
      null,
      null,
      null,
      null,
      null,
      "body.removeChild()",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "XD",
      null,
      null,
      null,
      null,
      null,
      "no",
      null,
      "probando cosas del final",
      null,
      "lo tenés ?",
      "pasalo",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "uf",
      null,
      "es que si no no voy a llegar",
      null,
      "cómo es electrónica ?",
      null,
      "quiero decír en qué andan ?",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null],

    //minuto22
    [null,
      null,
      null,
      null,
      null,
      "cool",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "jaja",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "que internacionales",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "bueeeeena",
      null,
      null,
      "ni que fuera obligatorio ver el partido",
      null,
      "encima de otra selección",
      null,
      "amonestaciones",
      "mínimo",
      null,
      null,
      "amonestación, para usar una expresión futbolera",
      null,
      null,
      null,
      null,
      null],

    //minuto23
    [change,
      "No me pareció que todo esté mal",
      null,
      "Pero me dió mucha tristesa el primero",
      null,
      "Ese palo mano de selfi me dio ganas de llorar posta",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Si, pero pasa no muchas manualidades",
      null,
      null,
      null,
      null,
      null,
      "La mano fue una clara muestra de nuestra generación aislada y exhibicionista",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "No bobis no es ina cartera para un espejo",
      null,
      "Es un sobre( asi se llama ese tipo de carteras) con un espejo,",
      null,
      null,
      "la boluda del video no le puso nada pero las.minas usamos carteras chicas",
      null,
      null,
      null,
      null,
      null,
      "Si muy",
      null,
      null,
      null,
      null,
      null,
      "Yo mas",
      "Lo sabias?",
      null,
      null,
      null,
      null,
      "Yo igual",
      null,
      "Chenmenfui a bañar",
      null,
      "😍",
      null,
      null,
      null,
      "Ooh",
      null],

    //minuto24
    [change,
      null,
      null,
      null,
      null,
      null,
      "hola!",
      "gracias!",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "si, el día del cierre seguro.",
      null,
      null,
      "y el 4/8 hacemos un encuentro más técnico con los ploters,",
      null,
      null,
      null,
      null,
      "ver como andan, \"imprimí lo q hiciste en processing\" etc...",
      null,
      null,
      null,
      null,
      "pero la curadora está de viaje en ese momento,",
      null,
      null,
      null,
      "así q las conversaciones las dejamos para el final",
      null,
      null,
      null,
      "igual yo voy a estar yendo,",
      null,
      "si te dan ganas en otro momento, arreglamos y nos vemos ahi.",
      null,
      null,
      null,
      null,
      null,
      "bueno, escribime y arreglamos, pla abre de mier a sab de 15 a 20hs.",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "tengo dos meses de reuniones atrasadas jeje",
      null,
      null,
      null,
      null,
      null],

    //minuto25
    [null,
      null,
      "o sea, tengo un montón de tiempo, pero muy salteado / intermitente",
      null,
      null,
      null,
      null,
      "pero juev o sábado seguro voy a estar en la galería...",
      null,
      null,
      "decime vos cuando sepas y vemos.",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "eso. dale, suerte en los finales.",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "nop.",
      null,
      null,
      "nuestra materia es solo de primer cuat.",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "nono. osea, img electronica 2 se da ahora en el segundo,",
      null,
      null,
      "pero nosotros no estamos en esa materia... ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null],

    //minuto26
    [change,
      "habrá certificados hoy?",
      null,
      "hay depa de alumnos?",
      null,
      null,
      "estoy terminando de subir mi entrega y salgo para caseros",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "saliendo!!!",
      null,
      "si tenés recreo... podrías pedir un certi?",
      null,
      null,
      null,
      "porfis",
      "porfis",
      null,
      null,
      null,
      null,
      null,
      null,
      "gracias Kvzi",
      null,
      null,
      null,
      null,
      null,
      "sí voy",
      null,
      null,
      "pero recién termino de subir todo al Drive para entregar",
      null,
      null,
      "estoy en REtiro",
      null,
      "odio al tren S Martín",
      null,
      "voy a por el 53 en Constitución",
      "gracias Kevz",
      null],

    //minuto27
    [change,
      "kev cuando vas a la facu ?",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "tengo algo para vos",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "hipermedial, no ?",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "ajajja, y se podría comer .. no lo recomiendo",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "hoy em acerco a la facu y te lo doy",
      null,
      null,
      null,
      null,
      null,
      null],

    //minuto28
    [change,
      "hola Kev, ya estoy saliendo para la facu",
      null,
      "che, no pude hacer el video",
      null,
      "digamos que ableton no soporta mi formato",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "si 😕",
      null,
      "no pude hacer nada",
      null,
      null,
      "lo exporté en quick time como leí y nada",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "no, no tengo los mails",
      null,
      "y estoy en plena mudanza y con muchas cosas",
      null,
      null,
      null,
      null,
      "gracias!!",
      null,
      "si podes darme una mano luego con ese tema, sería genial",
      null,
      "no se si ir 😕",
      "bien, mudándome",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "ah",
      "jaja",
      "ya mostraste?",
      null,
      null,
      null,
      "ahh",
      "okk",
      "ohh",
      null,
      "si",
      null,
      null],

    //minuto29
    [null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "pasa que yo saque una escena de una película de 2hs y media",
      null,
      "y me quedó como el ogt en el premier",
      null,
      null,
      null,
      null,
      null,
      "si",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "no se",
      "se ve mal",
      null,
      null,
      null,
      null,
      null,
      null,
      "ni idea xq como ya no me acuerdo cómo usarlo 🙍🏼💁🏼",
      null,
      null,
      null,
      null,
      null,
      null,
      "😓",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "si!!! tengop que terminar unos asuntos urgentes y te escribo, dale?",
      null,
      null,
      null],

    //minuto30
    [change,
      "ya terminaron de hangout no?",
      null,
      null,
      null,
      null,
      null,
      "si escribieron un resumen o algo me pasas?",
      null,
      null,
      "si tenes los resultados de los ejercicios me los pasas?",
      "gracias",
      "jajaja",
      null,
      null,
      "yo recien llego a casa tuve una fecha a beneficio en avellaneda",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "yo tambien...",
      null,
      null,
      "me sirve si me pasas unos screenshots de lo que tengan",
      null,
      "asi estudio y comparo",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "de una",
      "a ver",
      null,
      null,
      null,
      null,
      "de una genial, me doy una ducha y lo chequeo",
      null,
      "estoy quemadisimo de arte al aire libre yo...",
      null,
      null,
      null,
      "Si, re, pero no estoy ni ahi preparado para el parcial",
      null,
      "asique le tengo que meter ahora",
      null,
      null,
      null,
      null,
      null,
      "exacto",
      null,
      "cme doy una ducha para arrancar con eso",
      "jejeje"],

    //minuto31
    [change,
      "Hola ñeri como estas?",
      null,
      null,
      "Che vos tendras para pasarme la simulacion de la clase pasada?",
      null,
      null,
      "Estamos con agus las pe y no estamos pudoendo hacerla bien.",
      null,
      null,
      null,
      null,
      null,
      "La de la web",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "El circuito del proyecto",
      null,
      null,
      null,
      null,
      null,
      "Esacto",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Estamos cursando las mismas mal",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Muchas gracias kev",
      null,
      null,
      "Estabamos re trabados",
      null,
      null,
      null,
      null,
      null,
      null],

    //minuto32
    [change,
      "?",
      null,
      "yo no te saludé! que le pasa",
      null,
      null,
      null,
      null,
      null,
      "si te iba a decir que",
      null,
      null,
      "de la birra no vas  a decir nada?",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "ey que onda",
      null,
      "estoy saludando a todo el mundo",
      null,
      "a vos también te pasA?",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "cuando apoyo la flechita en alguien para abrir ventana de chat los saluda",
      "o sea",
      null,
      "no, pero probá esto",
      null,
      null,
      null,
      null,
      "apoyá a ver si aparece la manito",
      null,
      null,
      null,
      "y si das click para abrir",
      "los saluda!",
      null,
      null,
      null,
      null,
      "abre la ventana y automáticamente saluda",
      null,
      null,
      null,
      null,
      "probá conmigo",
      null],

    //minuto33
    [null,
      null,
      null,
      null,
      null,
      "barra derecha",
      null,
      "donde están los contactos",
      null,
      null,
      "en mi caso en gris porque tengo el chat cerrado",
      null,
      null,
      "pongo la flechita arriba de un contacto x",
      null,
      "sin dar click y me aparece la manito",
      null,
      null,
      "si doy click, abre ventana y manda automáticamente saludo",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "uh en mi caso si",
      null,
      "no puedo parar de saludar gente",
      null,
      null,
      "que gato, de donde me automatizó esto'",
      "bueno",
      "en fin",
      null,
      "birra si entonces",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "no, ya está ahora ya lo sé",
      null,
      "hasta ahora todos quieren birra",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "jajaja",
      "obvio"],

    //minuto34
    [change,
      null,
      null,
      null,
      null,
      null,
      "Kevin! Todo tranquilo, vos?",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Soy bibliotecario",
      null,
      "Trabajé con editores",
      null,
      null,
      null,
      "pero en la parte comercial",
      "no literatia.",
      null,
      null,
      null,
      null,
      null,
      null,
      "Igual si me das unos días intento ubicar algún editor",
      null,
      "y te pongo en contacto",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null],

    //minuto35
    [null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Te aconsejo igual hablar con alguien de edición",
      "jaja",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Avisame y te busco el contacto",
      null,
      null,
      "Yo creo que un editor te va a dar su idea",
      null,
      null,
      null,
      "y proponerte trabajar con su idea",
      null,
      "que es lógico",
      null,
      null,
      null,
      "porque al ser un profesional tiene su verdad",
      null,
      "no es que lo hace de pesado",
      null,
      null,
      null,
      null,
      null,
      "Pero sino charlar con estudiantes de edición es un golazo",
      null,
      null,
      "Igual no entendí si la charla la buscabas conmigo jaja",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null],

    //minuto36
    [change,
      null,
      null,
      null,
      null,
      null,
      "Kev😊",
      "Todo ok",
      "Vos?",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Jaja",
      "y bueno.",
      null,
      null,
      "Tenés que establecer los parámetros de objetividad",
      null,
      null,
      null,
      null,
      "Y cuáles son?",
      "Qué evaluás?",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null],

    //minuto37
    [null,
      "Sí.",
      null,
      "Van bien pero estoy un poco agotado la verdad.",
      null,
      null,
      "Tengo ganas de trabajar en otros espacios y niveles.",
      null,
      "Yo doy filosofía para niñxs.",
      null,
      null,
      "En un momento tenía desde sala de 4 años!",
      null,
      null,
      null,
      "Está buenísimo pero te deja exhausto",
      null,
      null,
      "y además la institución primaria e inicial",
      null,
      null,
      null,
      "es insoportable respecto de las formalidades.",
      null,
      null,
      null,
      null,
      "También me desalienta que es una responsabilidad gigante",
      null,
      null,
      "y se paga menos que lo demás.",
      null,
      null,
      null,
      "Me gustaría trabajar en algo más cercano al arte quizás",
      "no sé.",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Consideré hacer la maestría por ejemplo de la untref",
      "pero ni sé.",
      null,
      null,
      null,
      null,
      null,
      null,
      "Estoy con ganas de cambiar",
      null,
      null,
      "La propuesta con niñxs está alucinante didácticamente",
      null,
      null,
      null,
      null,
      "porque es filosofar con ellxs pero quedás de cama."],

    //minuto38
    [null,
      null,
      null,
      "Me fui curtiendo mucho con los años",
      null,
      null,
      null,
      "pero también dejando un poco todo lo que hacía con adultos.",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Dale obvio",
      null,
      "Lo que yo te dije",
      null,
      null,
      "no era respecto de incluir carteles de campañas electorales",
      null,
      "sino que te preguntaba si habías pensado",
      null,
      null,
      "en el contexto político en el que los situacionistas plantearon la deriva.",
      null,
      null,
      null,
      null],

    //minuto39
    [null,
      "El situacionismo era una práctica política concreta que",
      "por ejemplo",
      null,
      "cuestionaba la enajenación del arte",
      null,
      "so el placer como esferas específicas",
      null,
      "o separadas de la vida.",
      "O sea",
      null,
      "no era una propuesta estética",
      null,
      null,
      "o, en tanto propuesta estética pierde su sentido político.",
      "Jaja",
      null,
      "pensé que eta una pavada",
      null,
      null,
      null,
      "pero ahora que te voy escribiendo me doy cuenta de que por ahí da para largo.",
      null,
      "Yo soy bastante fan de Debord la verdad.",
      null,
      "Un día podríamos hacer una juntada para ver una peli suya",
      null,
      null,
      "y yo hago una introducción si les parece.",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Delectro supongo.",
      null,
      null,
      "No le veo relación muy clara con la cuestión del código",
      null,
      "(si con lenguaje pero eso es otra cosa)",
      null,
      "Mirate \"crítica de la separación\".",
      null,
      "Es un corto y es genial, es intenso igual.",
      null,
      null,
      null,
      null],

      //minuto40
      [change,
        null,
        null,
        null,
        null,
        "Que onda kevo",
        null,
        "Aca ensayando con el sub",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Re quiero",
        null,
        "Pero tengo el finao de cuestiones",
        null,
        "A que hora es?",
        "Sabes?",
        null,
        null,
        null,
        null,
        "Mmhhmhm me parece que no llego",
        null,
        "Re triste",
        null,
        null,
        null,
        null,
        null,
        "Taba re manija de ambisonics",
        null,
        "Osea a menos de que me tome primer9",
        null,
        null,
        null,
        null,
        null,
        null,
        "Pero no estoy en condiciones de exigir mucho a la catedra",
        null,
        null,
        "Si",
        "Re",
        null,
        "Che hablando de todo un poco",
        null,
        null,
        "Si sigue en pie la linea de esos llaveritxs pañuelo veree",
        null,
        "Me encargas uno?",
        null,
        null,
        null,
        null],

      //minuto41
      [change,
        "cuando ves lo que estás tipeando en Atom",
        null,
        "y te das cuenta que la situación social se filtra por todos lados",
        null,
        null,
        null,
        null,
        null,
        "body.removeChild()",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "XD",
        null,
        null,
        null,
        null,
        null,
        "no",
        null,
        "probando cosas del final",
        null,
        "lo tenés ?",
        "pasalo",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "uf",
        null,
        "es que si no no voy a llegar",
        null,
        "cómo es electrónica ?",
        null,
        "quiero decír en qué andan ?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto42
      [null,
        null,
        null,
        null,
        null,
        "cool",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "jaja",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "que internacionales",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "bueeeeena",
        null,
        null,
        "ni que fuera obligatorio ver el partido",
        null,
        "encima de otra selección",
        null,
        "amonestaciones",
        "mínimo",
        null,
        null,
        "amonestación, para usar una expresión futbolera",
        null,
        null,
        null,
        null,
        null],

      //minuto43
      [change,
        "No me pareció que todo esté mal",
        null,
        "Pero me dió mucha tristesa el primero",
        null,
        "Ese palo mano de selfi me dio ganas de llorar posta",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Si, pero pasa no muchas manualidades",
        null,
        null,
        null,
        null,
        null,
        "La mano fue una clara muestra de nuestra generación aislada y exhibicionista",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "No bobis no es ina cartera para un espejo",
        null,
        "Es un sobre( asi se llama ese tipo de carteras) con un espejo,",
        null,
        null,
        "la boluda del video no le puso nada pero las.minas usamos carteras chicas",
        null,
        null,
        null,
        null,
        null,
        "Si muy",
        null,
        null,
        null,
        null,
        null,
        "Yo mas",
        "Lo sabias?",
        null,
        null,
        null,
        null,
        "Yo igual",
        null,
        "Chenmenfui a bañar",
        null,
        "😍",
        null,
        null,
        null,
        "Ooh",
        null],

      //minuto44
      [change,
        null,
        null,
        null,
        null,
        null,
        "hola!",
        "gracias!",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "si, el día del cierre seguro.",
        null,
        null,
        "y el 4/8 hacemos un encuentro más técnico con los ploters,",
        null,
        null,
        null,
        null,
        "ver como andan, \"imprimí lo q hiciste en processing\" etc...",
        null,
        null,
        null,
        null,
        "pero la curadora está de viaje en ese momento,",
        null,
        null,
        null,
        "así q las conversaciones las dejamos para el final",
        null,
        null,
        null,
        "igual yo voy a estar yendo,",
        null,
        "si te dan ganas en otro momento, arreglamos y nos vemos ahi.",
        null,
        null,
        null,
        null,
        null,
        "bueno, escribime y arreglamos, pla abre de mier a sab de 15 a 20hs.",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "tengo dos meses de reuniones atrasadas jeje",
        null,
        null,
        null,
        null,
        null],

      //minuto45
      [null,
        null,
        "o sea, tengo un montón de tiempo, pero muy salteado / intermitente",
        null,
        null,
        null,
        null,
        "pero juev o sábado seguro voy a estar en la galería...",
        null,
        null,
        "decime vos cuando sepas y vemos.",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "eso. dale, suerte en los finales.",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "nop.",
        null,
        null,
        "nuestra materia es solo de primer cuat.",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "nono. osea, img electronica 2 se da ahora en el segundo,",
        null,
        null,
        "pero nosotros no estamos en esa materia... ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto46
      [change,
        "habrá certificados hoy?",
        null,
        "hay depa de alumnos?",
        null,
        null,
        "estoy terminando de subir mi entrega y salgo para caseros",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "saliendo!!!",
        null,
        "si tenés recreo... podrías pedir un certi?",
        null,
        null,
        null,
        "porfis",
        "porfis",
        null,
        null,
        null,
        null,
        null,
        null,
        "gracias Kvzi",
        null,
        null,
        null,
        null,
        null,
        "sí voy",
        null,
        null,
        "pero recién termino de subir todo al Drive para entregar",
        null,
        null,
        "estoy en REtiro",
        null,
        "odio al tren S Martín",
        null,
        "voy a por el 53 en Constitución",
        "gracias Kevz",
        null],

      //minuto47
      [change,
        "kev cuando vas a la facu ?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "tengo algo para vos",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "hipermedial, no ?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "ajajja, y se podría comer .. no lo recomiendo",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "hoy em acerco a la facu y te lo doy",
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto48
      [change,
        "hola Kev, ya estoy saliendo para la facu",
        null,
        "che, no pude hacer el video",
        null,
        "digamos que ableton no soporta mi formato",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "si 😕",
        null,
        "no pude hacer nada",
        null,
        null,
        "lo exporté en quick time como leí y nada",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "no, no tengo los mails",
        null,
        "y estoy en plena mudanza y con muchas cosas",
        null,
        null,
        null,
        null,
        "gracias!!",
        null,
        "si podes darme una mano luego con ese tema, sería genial",
        null,
        "no se si ir 😕",
        "bien, mudándome",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "ah",
        "jaja",
        "ya mostraste?",
        null,
        null,
        null,
        "ahh",
        "okk",
        "ohh",
        null,
        "si",
        null,
        null],

      //minuto49
      [null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "pasa que yo saque una escena de una película de 2hs y media",
        null,
        "y me quedó como el ogt en el premier",
        null,
        null,
        null,
        null,
        null,
        "si",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "no se",
        "se ve mal",
        null,
        null,
        null,
        null,
        null,
        null,
        "ni idea xq como ya no me acuerdo cómo usarlo 🙍🏼💁🏼",
        null,
        null,
        null,
        null,
        null,
        null,
        "😓",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "si!!! tengop que terminar unos asuntos urgentes y te escribo, dale?",
        null,
        null,
        null],

      //minuto50
      [change,
        "ya terminaron de hangout no?",
        null,
        null,
        null,
        null,
        null,
        "si escribieron un resumen o algo me pasas?",
        null,
        null,
        "si tenes los resultados de los ejercicios me los pasas?",
        "gracias",
        "jajaja",
        null,
        null,
        "yo recien llego a casa tuve una fecha a beneficio en avellaneda",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "yo tambien...",
        null,
        null,
        "me sirve si me pasas unos screenshots de lo que tengan",
        null,
        "asi estudio y comparo",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "de una",
        "a ver",
        null,
        null,
        null,
        null,
        "de una genial, me doy una ducha y lo chequeo",
        null,
        "estoy quemadisimo de arte al aire libre yo...",
        null,
        null,
        null,
        "Si, re, pero no estoy ni ahi preparado para el parcial",
        null,
        "asique le tengo que meter ahora",
        null,
        null,
        null,
        null,
        null,
        "exacto",
        null,
        "cme doy una ducha para arrancar con eso",
        "jejeje"],

      //minuto51
      [change,
        "Hola ñeri como estas?",
        null,
        null,
        "Che vos tendras para pasarme la simulacion de la clase pasada?",
        null,
        null,
        "Estamos con agus las pe y no estamos pudoendo hacerla bien.",
        null,
        null,
        null,
        null,
        null,
        "La de la web",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "El circuito del proyecto",
        null,
        null,
        null,
        null,
        null,
        "Esacto",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Estamos cursando las mismas mal",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Muchas gracias kev",
        null,
        null,
        "Estabamos re trabados",
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto52
      [change,
        "?",
        null,
        "yo no te saludé! que le pasa",
        null,
        null,
        null,
        null,
        null,
        "si te iba a decir que",
        null,
        null,
        "de la birra no vas  a decir nada?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "ey que onda",
        null,
        "estoy saludando a todo el mundo",
        null,
        "a vos también te pasA?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "cuando apoyo la flechita en alguien para abrir ventana de chat los saluda",
        "o sea",
        null,
        "no, pero probá esto",
        null,
        null,
        null,
        null,
        "apoyá a ver si aparece la manito",
        null,
        null,
        null,
        "y si das click para abrir",
        "los saluda!",
        null,
        null,
        null,
        null,
        "abre la ventana y automáticamente saluda",
        null,
        null,
        null,
        null,
        "probá conmigo",
        null],

      //minuto53
      [null,
        null,
        null,
        null,
        null,
        "barra derecha",
        null,
        "donde están los contactos",
        null,
        null,
        "en mi caso en gris porque tengo el chat cerrado",
        null,
        null,
        "pongo la flechita arriba de un contacto x",
        null,
        "sin dar click y me aparece la manito",
        null,
        null,
        "si doy click, abre ventana y manda automáticamente saludo",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "uh en mi caso si",
        null,
        "no puedo parar de saludar gente",
        null,
        null,
        "que gato, de donde me automatizó esto'",
        "bueno",
        "en fin",
        null,
        "birra si entonces",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "no, ya está ahora ya lo sé",
        null,
        "hasta ahora todos quieren birra",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "jajaja",
        "obvio"],

      //minuto54
      [change,
        null,
        null,
        null,
        null,
        null,
        "Kevin! Todo tranquilo, vos?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Soy bibliotecario",
        null,
        "Trabajé con editores",
        null,
        null,
        null,
        "pero en la parte comercial",
        "no literatia.",
        null,
        null,
        null,
        null,
        null,
        null,
        "Igual si me das unos días intento ubicar algún editor",
        null,
        "y te pongo en contacto",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto55
      [null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Te aconsejo igual hablar con alguien de edición",
        "jaja",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Avisame y te busco el contacto",
        null,
        null,
        "Yo creo que un editor te va a dar su idea",
        null,
        null,
        null,
        "y proponerte trabajar con su idea",
        null,
        "que es lógico",
        null,
        null,
        null,
        "porque al ser un profesional tiene su verdad",
        null,
        "no es que lo hace de pesado",
        null,
        null,
        null,
        null,
        null,
        "Pero sino charlar con estudiantes de edición es un golazo",
        null,
        null,
        "Igual no entendí si la charla la buscabas conmigo jaja",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto56
      [change,
        null,
        null,
        null,
        null,
        null,
        "Kev😊",
        "Todo ok",
        "Vos?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Jaja",
        "y bueno.",
        null,
        null,
        "Tenés que establecer los parámetros de objetividad",
        null,
        null,
        null,
        null,
        "Y cuáles son?",
        "Qué evaluás?",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null],

      //minuto57
      [null,
        "Sí.",
        null,
        "Van bien pero estoy un poco agotado la verdad.",
        null,
        null,
        "Tengo ganas de trabajar en otros espacios y niveles.",
        null,
        "Yo doy filosofía para niñxs.",
        null,
        null,
        "En un momento tenía desde sala de 4 años!",
        null,
        null,
        null,
        "Está buenísimo pero te deja exhausto",
        null,
        null,
        "y además la institución primaria e inicial",
        null,
        null,
        null,
        "es insoportable respecto de las formalidades.",
        null,
        null,
        null,
        null,
        "También me desalienta que es una responsabilidad gigante",
        null,
        null,
        "y se paga menos que lo demás.",
        null,
        null,
        null,
        "Me gustaría trabajar en algo más cercano al arte quizás",
        "no sé.",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Consideré hacer la maestría por ejemplo de la untref",
        "pero ni sé.",
        null,
        null,
        null,
        null,
        null,
        null,
        "Estoy con ganas de cambiar",
        null,
        null,
        "La propuesta con niñxs está alucinante didácticamente",
        null,
        null,
        null,
        null,
        "porque es filosofar con ellxs pero quedás de cama."],

      //minuto58
      [null,
        null,
        null,
        "Me fui curtiendo mucho con los años",
        null,
        null,
        null,
        "pero también dejando un poco todo lo que hacía con adultos.",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Dale obvio",
        null,
        "Lo que yo te dije",
        null,
        null,
        "no era respecto de incluir carteles de campañas electorales",
        null,
        "sino que te preguntaba si habías pensado",
        null,
        null,
        "en el contexto político en el que los situacionistas plantearon la deriva.",
        null,
        null,
        null,
        null],

      //minuto59
      [null,
        "El situacionismo era una práctica política concreta que",
        "por ejemplo",
        null,
        "cuestionaba la enajenación del arte",
        null,
        "so el placer como esferas específicas",
        null,
        "o separadas de la vida.",
        "O sea",
        null,
        "no era una propuesta estética",
        null,
        null,
        "o, en tanto propuesta estética pierde su sentido político.",
        "Jaja",
        null,
        "pensé que eta una pavada",
        null,
        null,
        null,
        "pero ahora que te voy escribiendo me doy cuenta de que por ahí da para largo.",
        null,
        "Yo soy bastante fan de Debord la verdad.",
        null,
        "Un día podríamos hacer una juntada para ver una peli suya",
        null,
        null,
        "y yo hago una introducción si les parece.",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Delectro supongo.",
        null,
        null,
        "No le veo relación muy clara con la cuestión del código",
        null,
        "(si con lenguaje pero eso es otra cosa)",
        null,
        "Mirate \"crítica de la separación\".",
        null,
        "Es un corto y es genial, es intenso igual.",
        null,
        null,
        null,
        null],
  ];
